name: quotewall
description: "Quote wall notifier"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.2.0
  logging: ^1.3.0
  timezone: ^0.10.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: BangersRegular
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
    - family: PressStart
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

  uses-material-design: true

  assets:
    - assets/fonts/Bangers-Regular.ttf
    - assets/fonts/PressStart2P-Regular.ttf
    - assets/images/
